name: d4_format
version: 1.0.0
description: Format numbers for human consumption.
repository: https://github.com/luizbarboza/d4_format

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0